spring.application.name=back-viatio

# O Koyeb injetará a porta automaticamente através da variável de ambiente $PORT.
# Se estiver rodando localmente no seu PC, usará a porta 8081 por padrão.
server.port=${PORT:8081}

# =======================================================
# PostgreSQL Configuration
# =======================================================
# Na nuvem (Koyeb): Crie uma variável chamada DATABASE_URL e cole o link JDBC fornecido pelo Neon.tech.
# Exemplo de link do Neon: jdbc:postgresql://ep-nome-xyz.us-east-2.aws.neon.tech/neondb
# Localmente (PC): Continuará usando o localhost automaticamente.
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/viatio}

# Na nuvem (Koyeb): Crie variáveis DB_USER e DB_PASS com o usuário e senha do Neon.tech.
# Localmente (PC): Continuará usando postgres e 1234.
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASS:1234}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações de proteção para banco Serverless (Neon)
# Permite que o pool feche todas as conexões quando não houver uso
spring.datasource.hikari.minimum-idle=0
# Tempo máximo que uma conexão ociosa pode ficar no pool antes de ser fechada (2 minutos)
# Deve ser menor que os 5 minutos de timeout do Neon para que o Hikari feche antes
spring.datasource.hikari.idle-timeout=120000
# Tempo máximo de vida de uma conexão ativa (5 minutos)
spring.datasource.hikari.max-lifetime=300000
# Tempo máximo de espera para o banco acordar (15 segundos)
# Garante margem de segurança para o cold start do Neon
spring.datasource.hikari.connection-timeout=15000

# =======================================================
# JPA / Hibernate Configuration
# =======================================================
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true

# =======================================================
# Segurança (JWT Secret)
# =======================================================
# Na nuvem (Koyeb): Crie uma variável JWT_SECRET com uma senha bem longa e complexa.
# Localmente (PC): Usará a chave de teste abaixo automaticamente.
api.security.token.secret=${JWT_SECRET:Viatio_secret_key_123}
